CREATE TYPE job_status AS ENUM ('queued', 'running', 'succeeded', 'failed');
CREATE TYPE task_status AS ENUM ('planned', 'ready', 'in_progress', 'completed', 'cancelled');

CREATE TABLE organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, slug text NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text NOT NULL UNIQUE, name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE memberships (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), user_id uuid NOT NULL REFERENCES users(id), role text NOT NULL, UNIQUE (organization_id, user_id));
CREATE TABLE campaigns (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), name text NOT NULL, offer text NOT NULL, icp text NOT NULL, configuration jsonb NOT NULL, readiness_score integer NOT NULL DEFAULT 0, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), campaign_id uuid NOT NULL REFERENCES campaigns(id), external_id text, name text NOT NULL, domain text, profile jsonb NOT NULL, readiness_score integer NOT NULL DEFAULT 0, suppressed boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (organization_id, campaign_id, external_id));
CREATE TABLE contact_points (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), account_id uuid NOT NULL REFERENCES accounts(id), type text NOT NULL, value text NOT NULL, source_type text NOT NULL, source_label text NOT NULL, source_url text, confidence real NOT NULL, consent_status text NOT NULL DEFAULT 'unknown', suppressed boolean NOT NULL DEFAULT false, discovered_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE tasks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), campaign_id uuid NOT NULL REFERENCES campaigns(id), account_id uuid NOT NULL REFERENCES accounts(id), status task_status NOT NULL DEFAULT 'planned', channel text NOT NULL, executor_type text NOT NULL, routing_rule_id text NOT NULL, card_snapshot jsonb NOT NULL, outcome jsonb, created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz);
CREATE TABLE jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), type text NOT NULL, status job_status NOT NULL DEFAULT 'queued', payload jsonb NOT NULL, idempotency_key text NOT NULL UNIQUE, attempts integer NOT NULL DEFAULT 0, max_attempts integer NOT NULL DEFAULT 3, run_after timestamptz NOT NULL DEFAULT now(), locked_at timestamptz, last_error text, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX jobs_claim_idx ON jobs (status, run_after, created_at);
CREATE TABLE audit_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), actor_id uuid, action text NOT NULL, entity_type text NOT NULL, entity_id text NOT NULL, metadata jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX audit_org_created_idx ON audit_events (organization_id, created_at DESC);
CREATE TABLE ai_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), task_type text NOT NULL, model text NOT NULL, prompt_version text NOT NULL, source_refs jsonb NOT NULL, structured_output jsonb, input_tokens integer, output_tokens integer, cost_micros integer, created_at timestamptz NOT NULL DEFAULT now());

-- Every application query must scope by organization_id. Production deployment
-- should additionally enable PostgreSQL RLS once session claims are wired.
