import {interpolate} from 'remotion';
import {company, queue, transcript} from '../fixtures';
import {clamp, reveal, settle} from '../utils/motion';
import {COLORS, FONT} from '../utils/timing';
import {Hairline, Label, Panel} from './Chrome';

export const CompanyQueue: React.FC<{frame: number}> = ({frame}) => <Panel style={{width: 190, height: 620}}><div style={{padding: 18}}><Label>Очередь · 12</Label><div style={{marginTop: 25, display: 'grid', gap: 10}}>{queue.map((item,i)=>{const p=settle(frame,i*4);return <div key={item.name} style={{padding:'15px 13px',borderRadius:14,background:item.active?'rgba(20,140,255,.14)':'rgba(255,255,255,.025)',boxShadow:item.active?'inset 2px 0 #148cff':'none',transform:`translateX(${(1-p)*-35}px)`,opacity:p}}><div style={{fontFamily:FONT,color:COLORS.white,fontSize:14,fontWeight:650}}>{item.name}</div><div style={{fontFamily:FONT,color:item.active?COLORS.cyan:COLORS.muted,fontSize:10,marginTop:7}}>{item.meta}</div></div>})}</div></div></Panel>;

export const CompanyContext: React.FC<{frame: number}> = ({frame}) => <Panel style={{width: 440, height: 620}}><div style={{padding: 28}}><Label tone="blue">AI контекст · готов</Label><div style={{fontFamily:FONT,color:COLORS.white,fontSize:35,fontWeight:680,letterSpacing:'-.045em',marginTop:20}}>{company.name}</div><div style={{fontFamily:FONT,color:COLORS.muted,fontSize:15,marginTop:7}}>{company.meta}</div><Hairline/><div style={{display:'grid',gap:20,marginTop:26}}>{[{k:'ЛПР',v:company.decisionMaker},{k:'Возможная потребность',v:company.need},{k:'Цель звонка',v:company.goal}].map((x,i)=>{const p=reveal(frame,12+i*7);return <div key={x.k} style={{opacity:p,transform:`translateY(${(1-p)*16}px)`}}><Label>{x.k}</Label><div style={{fontFamily:FONT,color:COLORS.white,fontSize:16,lineHeight:1.38,marginTop:7}}>{x.v}</div></div>})}</div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:25}}>{company.facts.map((x,i)=><span key={x} style={{fontFamily:FONT,fontSize:11,color:COLORS.cyan,padding:'8px 10px',borderRadius:20,background:'rgba(20,140,255,.1)',opacity:reveal(frame,40+i*5)}}>{x}</span>)}</div></div></Panel>;

export const LiveTranscript: React.FC<{frame: number}> = ({frame}) => <div style={{display:'grid',gap:16}}>{transcript.map((line,i)=>{const p=reveal(frame,25+i*18);return <div key={line.speaker} style={{opacity:p,transform:`translateY(${(1-p)*18}px)`}}><Label tone={i===1?'blue':'muted'}>{line.speaker}</Label><div style={{fontFamily:FONT,color:COLORS.white,fontSize:19,lineHeight:1.42,marginTop:6}}>{line.text}</div></div>})}</div>;

export const AiSuggestion: React.FC<{frame: number}> = ({frame}) => {const p=settle(frame,64,16);return <div style={{marginTop:20,padding:18,borderRadius:16,background:'linear-gradient(110deg,rgba(20,140,255,.18),rgba(20,140,255,.04))',boxShadow:'inset 0 0 0 1px rgba(101,199,255,.22)',transform:`translateY(${(1-p)*28}px) scale(${.96+.04*p})`,opacity:p}}><Label tone="blue">AI · следующий вопрос</Label><div style={{fontFamily:FONT,color:COLORS.white,fontSize:17,lineHeight:1.4,marginTop:9}}>Уточните срок договора и критерии выбора поставщика.</div></div>};

export const CallStageProgress: React.FC<{frame: number}> = ({frame}) => <div style={{display:'flex',alignItems:'center',gap:10}}>{['Контакт','Потребность','Следующий шаг'].map((x,i)=>{const active=frame>82?2:frame>42?1:0;return <div key={x} style={{display:'flex',alignItems:'center',gap:10}}><div style={{fontFamily:FONT,fontSize:11,color:i<=active?COLORS.white:COLORS.muted,padding:'8px 10px',borderRadius:20,background:i===active?'rgba(20,140,255,.18)':'transparent',boxShadow:i===active?'0 0 22px rgba(20,140,255,.25)':'none'}}>{x}</div>{i<2&&<div style={{width:24,height:1,background:i<active?COLORS.blue:COLORS.line}}/>}</div>})}</div>;

export const CallWorkspace: React.FC<{frame: number}> = ({frame}) => {const bars=Array.from({length:24},(_,i)=>10+Math.abs(Math.sin(frame*.22+i*.7))*38);return <Panel style={{width:630,height:760}}><div style={{padding:26}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><Label tone="blue">Звонок активен</Label><div style={{fontFamily:FONT,color:COLORS.white,fontSize:25,fontWeight:670,marginTop:8}}>{company.name}</div></div><div style={{fontFamily:FONT,color:COLORS.cyan,fontSize:26,fontVariantNumeric:'tabular-nums'}}>02:{String(18+Math.floor(frame/30)).padStart(2,'0')}</div></div><div style={{height:72,display:'flex',alignItems:'center',gap:5,margin:'22px 0'}}>{bars.map((h,i)=><div key={i} style={{width:5,height:h,borderRadius:4,background:i>15?COLORS.cyan:'rgba(101,199,255,.35)',transform:`scaleY(${interpolate(frame%12,[0,6,12],[.7,1,.7],clamp)})`}}/>)}</div><CallStageProgress frame={frame}/><Hairline/><LiveTranscript frame={frame}/><AiSuggestion frame={frame}/><div style={{display:'flex',justifyContent:'flex-end',marginTop:20}}><div style={{fontFamily:FONT,color:COLORS.white,fontSize:13,padding:'11px 17px',borderRadius:22,background:COLORS.blue}}>Зафиксировать результат</div></div></div></Panel>};
