import {interpolate} from 'remotion';
import {manager} from '../fixtures';
import {clamp, reveal, settle} from '../utils/motion';
import {COLORS, FONT} from '../utils/timing';
import {Label, Panel} from './Chrome';

export const QualityScore: React.FC<{frame: number}> = ({frame}) => {const p=settle(frame,12);const score=Math.round(interpolate(p,[0,1],[0,92]));return <div style={{position:'relative',width:220,height:220,display:'grid',placeItems:'center'}}><svg width="220" height="220" style={{position:'absolute',transform:'rotate(-90deg)'}}><circle cx="110" cy="110" r="88" fill="none" stroke="rgba(101,199,255,.1)" strokeWidth="10"/><circle cx="110" cy="110" r="88" fill="none" stroke={COLORS.blue} strokeWidth="10" strokeLinecap="round" strokeDasharray={553} strokeDashoffset={553*(1-.92*p)} style={{filter:'drop-shadow(0 0 12px rgba(20,140,255,.55))'}}/></svg><div style={{textAlign:'center'}}><div style={{fontFamily:FONT,color:COLORS.white,fontSize:72,fontWeight:680,letterSpacing:'-.06em'}}>{score}</div><Label>качество</Label></div></div>};
export const PayoutIndicator: React.FC<{frame: number}> = ({frame}) => <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginTop:30}}>{['Результат','Оценка','Начисление'].map((x,i)=><div key={x} style={{display:'contents'}}><div style={{fontFamily:FONT,color:i<=Math.floor(frame/18)?COLORS.white:COLORS.muted,fontSize:14}}>{x}</div>{i<2&&<div style={{position:'relative',height:1,width:65,background:COLORS.line,overflow:'hidden'}}><div style={{position:'absolute',width:25,height:1,background:COLORS.cyan,transform:`translateX(${interpolate(frame-i*15,[0,35],[-25,70],clamp)}px)`,boxShadow:'0 0 10px #65c7ff'}}/></div>}</div>)}</div>;
export const ManagerDashboard: React.FC<{frame: number}> = ({frame}) => <Panel style={{width:640,height:700}}><div style={{padding:28}}><div style={{display:'flex',justifyContent:'space-between'}}><div><Label tone="blue">Кампания · Июль</Label><div style={{fontFamily:FONT,color:COLORS.white,fontSize:28,fontWeight:680,marginTop:10}}>Обзор результата</div></div><Label>Demo data</Label></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12,marginTop:28}}>{[{k:'Качество',v:manager.quality},{k:'Встречи',v:manager.meetings},{k:'Начислено',v:manager.payout}].map((x,i)=>{const p=reveal(frame,8+i*7);return <div key={x.k} style={{gridColumn:i===2?'1 / 3':'auto',padding:22,borderRadius:18,background:'rgba(255,255,255,.035)',transform:`translateY(${(1-p)*20}px)`,opacity:p}}><Label>{x.k}</Label><div style={{fontFamily:FONT,color:i===2?COLORS.cyan:COLORS.white,fontSize:i===2?34:48,fontWeight:680,letterSpacing:'-.05em',marginTop:9}}>{x.v}</div></div>})}</div><div style={{marginTop:18,padding:22,borderRadius:18,background:'rgba(20,140,255,.08)'}}><div style={{display:'flex',justifyContent:'space-between'}}><div><Label>Оператор</Label><div style={{fontFamily:FONT,color:COLORS.white,fontSize:20,marginTop:7}}>{manager.operator}</div></div><div style={{fontFamily:FONT,color:COLORS.cyan,fontSize:13}}>89 / 100</div></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:18,marginTop:22}}><div><Label>Сильная сторона</Label><div style={{fontFamily:FONT,color:COLORS.white,fontSize:13,lineHeight:1.4,marginTop:7}}>{manager.strengths}</div></div><div><Label>Фокус развития</Label><div style={{fontFamily:FONT,color:COLORS.white,fontSize:13,lineHeight:1.4,marginTop:7}}>{manager.improvement}</div></div></div></div></div></Panel>;
